---
version: "3"
services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USERNAME: amine
      POSTERES_PWD: amine
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
volumes:
    postgres: